---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-minimal-rhel8:latest'

# used for hub credentials
#ansible_config: 'ansible.cfg'
dependencies:
  # python modules
  python: requirements.txt
  # collections
  #galaxy: requirements.yml
  # If you need to install dependencies with yum/dnf
  #system: bindep.txt
