---

- name: just digging
  hosts: localhost
  gather_facts: false
  tasks:
  - name: lookup redhat.com and set fact
    ansible.builtin.set_fact:
      redhatdotcom_ip: "{{ lookup('community.general.dig', 'redhat.com') }}"

  - name: print redhat.com ip
    ansible.builtin.debug:
      msg: redhat.com resolves to {{ redhatdotcom_ip }}
