---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:1.0.1-24'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8:1.0.1-39'

# used for hub credentials
#ansible_config: 'ansible.cfg'
dependencies:
  # python modules
  python: requirements.txt
  # collections
  #galaxy: requirements.yml
  # If you need to install dependencies with yum/dnf
  #system: bindep.txt
